-- Script untuk menambahkan kolom yang dibutuhkan halaman Additional Information
-- Jalankan jika kolom-kolom berikut belum ada di TMS_NEW.dbo.TMS_TC_TOOL_DRAWING_ENGIN

USE TMS_NEW;
GO

-- Tambah kolom MATERIAL_ID (FK ke TMS_M_MATERIAL)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_MATERIAL_ID')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_MATERIAL_ID INT NULL;
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name='FK_TMS_TC_TOOL_DRAW_ENGIN_MATERIAL')
    BEGIN
        ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN
        ADD CONSTRAINT FK_TMS_TC_TOOL_DRAW_ENGIN_MATERIAL FOREIGN KEY (TD_MATERIAL_ID) REFERENCES TMS_M_MATERIAL(MATERIAL_ID);
    END
END
GO

-- Tambah kolom MAKER_ID
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_MAKER_ID')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_MAKER_ID INT NULL;
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name='FK_TMS_TC_TOOL_DRAW_ENGIN_MAKER')
    BEGIN
        ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN
        ADD CONSTRAINT FK_TMS_TC_TOOL_DRAW_ENGIN_MAKER FOREIGN KEY (TD_MAKER_ID) REFERENCES TMS_M_MAKER(MAKER_ID);
    END
END
GO

-- Tambah kolom jumlah & harga tooling
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_MIN_QTY')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_MIN_QTY INT NULL;
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_REPLENISH_QTY')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_REPLENISH_QTY INT NULL;
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_PRICE')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_PRICE DECIMAL(18,2) NULL;
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_TOOL_LIFE')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_TOOL_LIFE INT NULL;
END
GO

-- Kolom urutan & remarks
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_SEQUENCE')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_SEQUENCE INT NULL;
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TMS_TC_TOOL_DRAWING_ENGIN' AND COLUMN_NAME='TD_DESCRIPTION')
BEGIN
    ALTER TABLE TMS_TC_TOOL_DRAWING_ENGIN ADD TD_DESCRIPTION NVARCHAR(MAX) NULL;
END
GO

PRINT 'Alter selesai: kolom Additional Information siap.';
GO

