-- Script untuk menambahkan kolom baru ke tabel TMS_TC_TOOL_BOM_ENGIN
-- Jalankan script ini jika kolom-kolom berikut belum ada di database

USE TMS_DB;
GO

-- Cek dan tambah kolom PRODUCT_ID (FK ke TMS_M_PRODUCT)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'PRODUCT_ID')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD PRODUCT_ID INT NULL;
    
    -- Tambah Foreign Key jika belum ada
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys 
                   WHERE name = 'FK_TMS_TC_TOOL_BOM_ENGIN_PRODUCT')
    BEGIN
        ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
        ADD CONSTRAINT FK_TMS_TC_TOOL_BOM_ENGIN_PRODUCT 
        FOREIGN KEY (PRODUCT_ID) REFERENCES TMS_M_PRODUCT(PRODUCT_ID);
    END
END
GO

-- Cek dan tambah kolom PROCESS_ID (FK ke TMS_M_OPERATION)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'PROCESS_ID')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD PROCESS_ID INT NULL;
    
    -- Tambah Foreign Key jika belum ada
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys 
                   WHERE name = 'FK_TMS_TC_TOOL_BOM_ENGIN_PROCESS')
    BEGIN
        ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
        ADD CONSTRAINT FK_TMS_TC_TOOL_BOM_ENGIN_PROCESS 
        FOREIGN KEY (PROCESS_ID) REFERENCES TMS_M_OPERATION(OPERATION_ID);
    END
END
GO

-- Cek dan tambah kolom MACHINE_GROUP_ID (FK ke TMS_M_MACHINES)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'MACHINE_GROUP_ID')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD MACHINE_GROUP_ID INT NULL;
    
    -- Tambah Foreign Key jika belum ada
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys 
                   WHERE name = 'FK_TMS_TC_TOOL_BOM_ENGIN_MACHINE_GROUP')
    BEGIN
        ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
        ADD CONSTRAINT FK_TMS_TC_TOOL_BOM_ENGIN_MACHINE_GROUP 
        FOREIGN KEY (MACHINE_GROUP_ID) REFERENCES TMS_M_MACHINES(MACHINE_ID);
    END
END
GO

-- Cek dan tambah kolom EFFECTIVE_DATE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'EFFECTIVE_DATE')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD EFFECTIVE_DATE DATETIME NULL;
END
GO

-- Cek dan tambah kolom CHANGE_SUMMARY
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'CHANGE_SUMMARY')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD CHANGE_SUMMARY NVARCHAR(MAX) NULL;
END
GO

-- Cek dan tambah kolom DRAWING
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'TMS_TC_TOOL_BOM_ENGIN' 
               AND COLUMN_NAME = 'DRAWING')
BEGIN
    ALTER TABLE TMS_TC_TOOL_BOM_ENGIN
    ADD DRAWING NVARCHAR(255) NULL;
END
GO

PRINT 'Script selesai. Kolom baru telah ditambahkan ke TMS_TC_TOOL_BOM_ENGIN jika belum ada.';
GO

