ALTER TABLE [dbo].[MS_ACTION_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_MS_ACTION_ITEM_MS_ACTION_CATEGORY] FOREIGN KEY([AI_AC_ID])
REFERENCES [dbo].[MS_ACTION_CATEGORY] ([AC_ID])
GO
ALTER TABLE [dbo].[MS_CAUSE_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_MS_CAUSE_ITEM_MS_ACTION_CATEGORY] FOREIGN KEY([CI_AC_ID])
REFERENCES [dbo].[MS_ACTION_CATEGORY] ([AC_ID])
GO
ALTER TABLE [dbo].[MS_CAUSE_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_MS_CAUSE_ITEM_MS_CAUSE_CATEGORY] FOREIGN KEY([CI_CC_ID])
REFERENCES [dbo].[MS_CAUSE_CATEGORY] ([CC_ID])
GO
ALTER TABLE [dbo].[MS_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_MS_MATERIAL_MS_UOM] FOREIGN KEY([MAT_UNIT])
REFERENCES [dbo].[MS_UOM] ([UOM_ID])
GO
ALTER TABLE [dbo].[MS_PART_MEMBERS]  WITH NOCHECK ADD  CONSTRAINT [FK_MS_PART_CHILD_CHILD_MS_PARTS] FOREIGN KEY([PARTM_CHILD_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[MS_PART_MEMBERS]  WITH CHECK ADD  CONSTRAINT [FK_MS_PART_CHILD_PARENT_MS_PARTS] FOREIGN KEY([PARTM_PARENT_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[MS_PARTS]  WITH CHECK ADD  CONSTRAINT [FK_MS_PARTS_MS_CUSTOMER] FOREIGN KEY([PART_CUS_ID])
REFERENCES [dbo].[MS_CUSTOMER] ([CUS_ID])
GO
ALTER TABLE [dbo].[MS_PARTS]  WITH CHECK ADD  CONSTRAINT [FK_MS_PARTS_MS_UOM] FOREIGN KEY([PART_UNITS])
REFERENCES [dbo].[MS_UOM] ([UOM_ID])
GO
ALTER TABLE [dbo].[MS_PERMISSIONS_PAGE]  WITH CHECK ADD  CONSTRAINT [FK_MS_PAGE_PERMISSIONS_MS_PERMISSIONS] FOREIGN KEY([PP_PERM_ID])
REFERENCES [dbo].[MS_PERMISSIONS] ([PERM_ID])
GO
ALTER TABLE [dbo].[MS_PERMISSIONS_PAGE]  WITH CHECK ADD  CONSTRAINT [FK_MS_PAGE_PERMISSIONS_MS_SUBMODULE] FOREIGN KEY([PP_SUBMOD_ID])
REFERENCES [dbo].[MS_SUBMODULE] ([SUBMOD_ID])
GO
ALTER TABLE [dbo].[MS_SUBMODULE]  WITH CHECK ADD  CONSTRAINT [FK_MS_SUBMODULE_MS_MODULE] FOREIGN KEY([SUBMOD_MOD_ID])
REFERENCES [dbo].[MS_MODULE] ([MOD_ID])
GO
ALTER TABLE [dbo].[MS_SUBMODULE_ACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_MS_SUBMODULE_ACTIONS_MS_SUBMODULE] FOREIGN KEY([SMA_SM_ID])
REFERENCES [dbo].[MS_SUBMODULE] ([SUBMOD_ID])
GO
ALTER TABLE [dbo].[MS_SUBMODULE_FORMATS]  WITH CHECK ADD  CONSTRAINT [FK_MS_SUBMODULE_FORMAT_MS_SUBMODULE] FOREIGN KEY([SMF_SM_ID])
REFERENCES [dbo].[MS_SUBMODULE] ([SUBMOD_ID])
GO
ALTER TABLE [dbo].[MS_SUBMODULE_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_MS_SUBMODULE_PERMISSIONS_MS_PERMISSIONS] FOREIGN KEY([SMP_PERM_ID])
REFERENCES [dbo].[MS_PERMISSIONS] ([PERM_ID])
GO
ALTER TABLE [dbo].[MS_SUBMODULE_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_MS_SUBMODULE_PERMISSIONS_MS_SUBMODULE] FOREIGN KEY([SMP_SUBMOD_ID])
REFERENCES [dbo].[MS_SUBMODULE] ([SUBMOD_ID])
GO
ALTER TABLE [dbo].[MS_USERS_OPERATION]  WITH CHECK ADD  CONSTRAINT [FK_MS_USERS_OPERATION_MS_OPERATION] FOREIGN KEY([USROP_OP_ID])
REFERENCES [dbo].[MS_OPERATION] ([OP_ID])
GO
ALTER TABLE [dbo].[MS_USERS_OPERATION]  WITH CHECK ADD  CONSTRAINT [FK_MS_USERS_OPERATION_MS_USERS] FOREIGN KEY([USROP_USR_ID])
REFERENCES [dbo].[MS_USERS] ([USR_ID])
GO
ALTER TABLE [dbo].[MS_VIEW]  WITH CHECK ADD  CONSTRAINT [FK_MS_VIEW_MS_SUBMODULE] FOREIGN KEY([VW_SUBMOD_ID])
REFERENCES [dbo].[MS_SUBMODULE] ([SUBMOD_ID])
GO
ALTER TABLE [dbo].[MS_VIEW_FIELDS]  WITH CHECK ADD  CONSTRAINT [FK_MS_VIEW_FIELDS_MS_FIELDS] FOREIGN KEY([VF_FD_ID])
REFERENCES [dbo].[MS_FIELDS] ([FD_ID])
GO
ALTER TABLE [dbo].[MS_VIEW_FIELDS]  WITH CHECK ADD  CONSTRAINT [FK_MS_VIEW_FIELDS_MS_VIEW] FOREIGN KEY([VF_VW_ID])
REFERENCES [dbo].[MS_VIEW] ([VW_ID])
GO
ALTER TABLE [dbo].[MS_VIEW_FILTERS]  WITH CHECK ADD  CONSTRAINT [FK_MS_VIEW_FILTERS_MS_FIELDS] FOREIGN KEY([VFR_FD_ID])
REFERENCES [dbo].[MS_FIELDS] ([FD_ID])
GO
ALTER TABLE [dbo].[MS_VIEW_FILTERS]  WITH CHECK ADD  CONSTRAINT [FK_MS_VIEW_FILTERS_MS_VIEW] FOREIGN KEY([VFR_VW_ID])
REFERENCES [dbo].[MS_VIEW] ([VW_ID])
GO
ALTER TABLE [dbo].[NS_EVENT_DEFINITIONS]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENTS_APPLICATIONS] FOREIGN KEY([EVT_APP_ID])
REFERENCES [dbo].[NS_APPLICATIONS] ([APP_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NS_EVENT_DELIVERY_CHANNEL]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENT_DELIVERY_CHANNEL_DELIVERY_CHANNEL] FOREIGN KEY([EVTDLVC_DLVC_ID])
REFERENCES [dbo].[NS_DELIVERY_CHANNEL] ([DLVC_ID])
GO
ALTER TABLE [dbo].[NS_EVENT_DELIVERY_CHANNEL]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENT_DELIVERY_CHANNEL_EVENTS] FOREIGN KEY([EVTDLVC_EVT_ID])
REFERENCES [dbo].[NS_EVENT_DEFINITIONS] ([EVT_ID])
GO
ALTER TABLE [dbo].[NS_EVENT_PARAM]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENT_PARAM_EVENT_PARAM_TYPE] FOREIGN KEY([EVTP_FIELD_TYPE])
REFERENCES [dbo].[NS_EVENT_PARAM_TYPE] ([EVTP_TYPE_ID])
GO
ALTER TABLE [dbo].[NS_EVENT_PARAM]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENT_PARAM_EVENTS] FOREIGN KEY([EVTP_EVT_ID])
REFERENCES [dbo].[NS_EVENT_DEFINITIONS] ([EVT_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIBER_CLASS]  WITH CHECK ADD  CONSTRAINT [FK_SUBSCRIBER_CLASS_DELIVERY_CHANNEL] FOREIGN KEY([SBCC_DLVC_ID])
REFERENCES [dbo].[NS_DELIVERY_CHANNEL] ([DLVC_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_DELIVERY_CHANNEL]  WITH NOCHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_DELIVERY_CHANNEL_DELIVERY_CHANNEL] FOREIGN KEY([SBCRDC_DLVC_ID])
REFERENCES [dbo].[NS_DELIVERY_CHANNEL] ([DLVC_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_DELIVERY_CHANNEL]  WITH NOCHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_DELIVERY_CHANNEL_SUBSCRIPTION] FOREIGN KEY([SBCRDC_SBCR_ID])
REFERENCES [dbo].[NS_SUBSCRIPTIONS] ([SBCR_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_FIELD_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_FIELD_VALUE_SUBSCRIPTION_FIELDS] FOREIGN KEY([SBCRFV_SBCRF_ID])
REFERENCES [dbo].[NS_SUBSCRIPTION_FIELDS] ([SBCRF_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_FIELDS]  WITH NOCHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_FIELDS_EVENT_PARAM] FOREIGN KEY([SBCRF_EVTP_ID])
REFERENCES [dbo].[NS_EVENT_PARAM] ([EVTP_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_FIELDS]  WITH CHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_FIELDS_SUBSCRIPTION] FOREIGN KEY([SBCRF_SBCR_ID])
REFERENCES [dbo].[NS_SUBSCRIPTIONS] ([SBCR_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_SUBSCRIBER_CLASS]  WITH CHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_SUBSCRIBER_CLASS_SUBCRIBER_GROUP] FOREIGN KEY([SSBRSC_SBCG_ID])
REFERENCES [dbo].[NS_SUBSCRIBER_GROUP] ([SBCG_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_SUBSCRIBER_CLASS]  WITH CHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_SUBSCRIBER_CLASS_SUBSCRIBER_CLASS] FOREIGN KEY([SSBRSC_SBCC_ID])
REFERENCES [dbo].[NS_SUBSCRIBER_CLASS] ([SBCC_ID])
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTION_SUBSCRIBER_CLASS]  WITH NOCHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_SUBSCRIBER_CLASS_SUBSCRIPTION] FOREIGN KEY([SSBRSC_SBCR_ID])
REFERENCES [dbo].[NS_SUBSCRIPTIONS] ([SBCR_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NS_SUBSCRIPTIONS]  WITH NOCHECK ADD  CONSTRAINT [FK_SUBSCRIPTION_EVENTS] FOREIGN KEY([SBCR_EVT_ID])
REFERENCES [dbo].[NS_EVENT_DEFINITIONS] ([EVT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TMS_ASSIGNED_TOOLS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_ASSIGNED_TOOLS_TMS_TOOL_ASSIGNMENT] FOREIGN KEY([ASSGN_TASGN_ID])
REFERENCES [dbo].[TMS_TOOL_ASSIGNMENT] ([TASGN_ID])
GO
ALTER TABLE [dbo].[TMS_ORDERING]  WITH CHECK ADD  CONSTRAINT [FK_TMS_ORDERING_MS_MAKER] FOREIGN KEY([ORD_MAKER_ID])
REFERENCES [dbo].[MS_MAKER] ([MAKER_ID])
GO
ALTER TABLE [dbo].[TMS_ORDERING_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_ORDERING_ITEMS_TMS_ORDERING] FOREIGN KEY([ORDI_ORD_ID])
REFERENCES [dbo].[TMS_ORDERING] ([ORD_ID])
GO
ALTER TABLE [dbo].[TMS_ORDERING_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_ORDERING_ITEMS_TMS_REQUISITION] FOREIGN KEY([ORDI_RQ_ID])
REFERENCES [dbo].[TMS_REQUISITION] ([RQ_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_MS_MAKER] FOREIGN KEY([RQ_MAKER_ID])
REFERENCES [dbo].[MS_MAKER] ([MAKER_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_MS_PARTS] FOREIGN KEY([RQ_PART_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_TMS_TOOL_INVENTORY] FOREIGN KEY([RQ_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([RQ_DWG_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_TMS_TOOL_SCRAP] FOREIGN KEY([RQ_SCRAP_ID])
REFERENCES [dbo].[TMS_TOOL_SCRAP] ([SCRAP_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_BOM_MLR]  WITH CHECK ADD  CONSTRAINT [FK_TMS_CURRINV_ALLOCATION_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([RQBMMLR_BOM_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_BOM_MLR]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_BOM_MLR_TMS_REQUISITION_DRAWING_ML] FOREIGN KEY([RQBMMLR_RQDWGML_ID])
REFERENCES [dbo].[TMS_REQUISITION_DRAWING_ML] ([RQDWGML_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_DRAWING_ML]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_CURRINV_TMS_REQUISITION] FOREIGN KEY([RQDWGML_RQ_ID])
REFERENCES [dbo].[TMS_REQUISITION] ([RQ_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_DRAWING_MLR]  WITH CHECK ADD  CONSTRAINT [FK_TMS_CURRINV_MLR_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([RQDWGMLR_DWG_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_DRAWING_MLR]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_DRAWING_MLR_TMS_REQUISITION_DRAWING_ML] FOREIGN KEY([RQDWGMLR_RQDWGML_ID])
REFERENCES [dbo].[TMS_REQUISITION_DRAWING_ML] ([RQDWGML_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_NOT_REPAIRABLE_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_NOT_REPAIRABLE_TOOL_TMS_REQUISITION_DRAWING_ML] FOREIGN KEY([RQNRT_RQDWGML_ID])
REFERENCES [dbo].[TMS_REQUISITION_DRAWING_ML] ([RQDWGML_ID])
GO
ALTER TABLE [dbo].[TMS_REQUISITION_NOT_REPAIRABLE_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TMS_REQUISITION_NOT_REPAIRABLE_TOOL_TMS_TOOL_INVENTORY] FOREIGN KEY([RQNRT_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_SCRAP_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_SCRAP_ATTACHMENT_TMS_TOOL_SCRAP] FOREIGN KEY([SCRAPATT_SCRAP_ID])
REFERENCES [dbo].[TMS_TOOL_SCRAP] ([SCRAP_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_ASSIGNMENT_MS_MACHINES] FOREIGN KEY([TASGN_MAC_ID])
REFERENCES [dbo].[MS_MACHINES] ([MAC_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_ASSIGNMENT_MS_OPERATION] FOREIGN KEY([TASGN_OP_ID])
REFERENCES [dbo].[MS_OPERATION] ([OP_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_ASSIGNMENT_MS_PARTS] FOREIGN KEY([TASGN_PART_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_ASSIGNMENT_TMS_TOOLSETS] FOREIGN KEY([TASGN_TSET_ID])
REFERENCES [dbo].[TMS_TOOLSETS] ([TSET_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_MS_MAKER] FOREIGN KEY([INV_MAKER_ID])
REFERENCES [dbo].[MS_MAKER] ([MAKER_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_MS_MATERIAL] FOREIGN KEY([INV_MAT_ID])
REFERENCES [dbo].[MS_MATERIAL] ([MAT_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_MS_STORAGE_LOCATION] FOREIGN KEY([INV_SL_ID])
REFERENCES [dbo].[MS_STORAGE_LOCATION] ([SL_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_TMS_ORDERING_ITEMS] FOREIGN KEY([INV_ORDI_ID])
REFERENCES [dbo].[TMS_ORDERING_ITEMS] ([ORDI_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_TMS_REQUISITION] FOREIGN KEY([INV_REPLACED_BY])
REFERENCES [dbo].[TMS_REQUISITION] ([RQ_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_TMS_TOOL_ASSIGNED_TOOLS] FOREIGN KEY([INV_ASSGN_ID])
REFERENCES [dbo].[TMS_ASSIGNED_TOOLS] ([ASSGN_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([INV_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_INVENTORY_TMS_WORKORDER] FOREIGN KEY([INV_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_PARTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_PARTS_MS_PARTS] FOREIGN KEY([TMLP_PART_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_MS_MACHINES] FOREIGN KEY([MLR_MACG_ID])
REFERENCES [dbo].[MS_MACHINES] ([MAC_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_MS_MAKER] FOREIGN KEY([MLR_MAKER_ID])
REFERENCES [dbo].[MS_MAKER] ([MAKER_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_MS_MATERIAL] FOREIGN KEY([MLR_MAT_ID])
REFERENCES [dbo].[MS_MATERIAL] ([MAT_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_MS_OPERATION] FOREIGN KEY([MLR_OP_ID])
REFERENCES [dbo].[MS_OPERATION] ([OP_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_MS_TOOL_CLASS] FOREIGN KEY([MLR_TC_ID])
REFERENCES [dbo].[MS_TOOL_CLASS] ([TC_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_MASTER_LIST_REV]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_MASTER_LIST_REV_TMS_TOOL_MASTER_LIST] FOREIGN KEY([MLR_ML_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST] ([ML_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_PLANNING]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_PLANNING_MS_MACHINES] FOREIGN KEY([TP_MAC_ID])
REFERENCES [dbo].[MS_MACHINES] ([MAC_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_PLANNING]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_PLANNING_MS_OPERATION] FOREIGN KEY([TP_OP_ID])
REFERENCES [dbo].[MS_OPERATION] ([OP_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_PLANNING]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_PLANNING_MS_PARTS] FOREIGN KEY([TP_PART_ID])
REFERENCES [dbo].[MS_PARTS] ([PART_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_PLANNING]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_PLANNING_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([TP_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_SCRAP]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_SCRAP_MS_REASON] FOREIGN KEY([SCRAP_REASON_ID])
REFERENCES [dbo].[MS_REASON] ([REASON_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_SCRAP]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_SCRAP_TMS_TOOL_INVENTORY] FOREIGN KEY([SCRAP_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_SPEC]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_SPEC_TMS_ATTRIBUTES] FOREIGN KEY([TLSPEC_ATTR_ID])
REFERENCES [dbo].[TMS_ATTRIBUTES] ([ATTR_ID])
GO
ALTER TABLE [dbo].[TMS_TOOL_SPEC]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOL_SPEC_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([TLSPEC_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_TOOLSET_COMPONENTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOLSET_COMPONENTS_TMS_TOOL_INVENTORY] FOREIGN KEY([TSCOM_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_TOOLSET_COMPOSITIONS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOLSET_COMPOSITIONS_TMS_TOOL_INVENTORY] FOREIGN KEY([TSCOMP_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_TOOLSET_COMPOSITIONS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOLSET_COMPOSITIONS_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([TSCOMP_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_TOOLSET_COMPOSITIONS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOLSET_COMPOSITIONS_TMS_TOOLSETS] FOREIGN KEY([TSCOMP_TSET_ID])
REFERENCES [dbo].[TMS_TOOLSETS] ([TSET_ID])
GO
ALTER TABLE [dbo].[TMS_TOOLSETS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_TOOLSETS_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([TSET_BOM_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
ALTER TABLE [dbo].[TMS_USAGE_LOG]  WITH CHECK ADD  CONSTRAINT [FK_TMS_USAGE_LOG_MS_MACHINES] FOREIGN KEY([ULOG_MAC_ID])
REFERENCES [dbo].[MS_MACHINES] ([MAC_ID])
GO
ALTER TABLE [dbo].[TMS_USAGE_LOG]  WITH CHECK ADD  CONSTRAINT [FK_TMS_USAGE_LOG_TMS_WORK_ACTIVITIES] FOREIGN KEY([ULOG_WA_ID])
REFERENCES [dbo].[TMS_WORK_ACTIVITIES] ([WA_ID])
GO
ALTER TABLE [dbo].[TMS_USAGE_LOG]  WITH CHECK ADD  CONSTRAINT [FK_TMS_USAGE_LOG_TMS_WORKORDER] FOREIGN KEY([ULOG_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_WO_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_ATTACHMENT_TMS_WO_ATTACHMENT] FOREIGN KEY([WOATT_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_WO_EXTERNAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_EXTERNAL_COSTS_MS_SUPPLIER] FOREIGN KEY([EXTCOST_SUP_ID])
REFERENCES [dbo].[MS_SUPPLIER] ([SUP_ID])
GO
ALTER TABLE [dbo].[TMS_WO_EXTERNAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_EXTERNAL_COSTS_TMS_WORK_ACTIVITIES] FOREIGN KEY([EXTCOST_WA_ID])
REFERENCES [dbo].[TMS_WORK_ACTIVITIES] ([WA_ID])
GO
ALTER TABLE [dbo].[TMS_WO_EXTERNAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_EXTERNAL_COSTS_TMS_WORKORDER] FOREIGN KEY([EXTCOST_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MATERIAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MATERIAL_COSTS_MS_MATERIAL] FOREIGN KEY([MATCOST_MAT_ID])
REFERENCES [dbo].[MS_MATERIAL] ([MAT_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MATERIAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MATERIAL_COSTS_TMS_WORK_ACTIVITIES] FOREIGN KEY([MATCOST_WA_ID])
REFERENCES [dbo].[TMS_WORK_ACTIVITIES] ([WA_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MATERIAL_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MATERIAL_COSTS_TMS_WORKORDER] FOREIGN KEY([MATCOST_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MCMH_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MCMH_COSTS_MS_MACHINES] FOREIGN KEY([MCMHCOST_MAC_ID])
REFERENCES [dbo].[MS_MACHINES] ([MAC_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MCMH_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MCMH_COSTS_TMS_WORK_ACTIVITIES] FOREIGN KEY([MCMHCOST_WA_ID])
REFERENCES [dbo].[TMS_WORK_ACTIVITIES] ([WA_ID])
GO
ALTER TABLE [dbo].[TMS_WO_MCMH_COSTS]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WO_MCMH_COSTS_TMS_WORKORDER] FOREIGN KEY([MCMHCOST_WO_ID])
REFERENCES [dbo].[TMS_WORKORDER] ([WO_ID])
GO
ALTER TABLE [dbo].[TMS_WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WORKORDER_TMS_TOOL_INVENTORY] FOREIGN KEY([WO_INV_ID])
REFERENCES [dbo].[TMS_TOOL_INVENTORY] ([INV_ID])
GO
ALTER TABLE [dbo].[TMS_WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_TMS_WORKORDER_TMS_TOOL_MASTER_LIST_REV] FOREIGN KEY([WO_MLR_ID])
REFERENCES [dbo].[TMS_TOOL_MASTER_LIST_REV] ([MLR_ID])
GO
